import type { Metadata } from 'next'
import './globals.css'
import Dock from '@/_components/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body className="bg-zinc-100 scroll-smooth">
        <Dock />
        {children}
      </body>
    </html>
  )
}
