import type { Metadata } from 'next'
import './globals.css'
import Dock from '@/_components/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html >
      <head><Dock /></head>
      <body className='bg-zinc-100'>{children}</body>
    </html>
  )
}
