import type { Metadata } from 'next'
import './globals.css'
import Navigation from '@/_components/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <Navigation />
      <body>{children}</body>
    </div>
  )
}
